import Link from "next/link";
import { CalendarDays, Clock3, Eye, Headphones, Plus } from "lucide-react";
import { listPodcastEpisodes } from "@/app/lib/podcast-repository";
import { MediaMoreActions } from "@/app/admin/(protected)/content/media-more-actions";
import styles from "../content/admin-library-reference.module.css";

export default async function AdminPodcastPage() {
  const episodes = await listPodcastEpisodes(false);
  const published = episodes.filter((episode) => episode.status === "published").length;
  const drafts = episodes.length - published;
  return <section className={styles.library}><div className={styles.heading}><div><h1>Podcast</h1><p>Write and manage audio episodes, transcripts, and show notes.</p></div></div><div className={styles.toolbar}><nav className={styles.tabs}><span className={`${styles.tab} ${styles.tabActive}`}>All ({episodes.length})</span><span className={styles.tab}>Published ({published})</span><span className={styles.tab}>Drafts ({drafts})</span><span className={styles.tab}>Archived (0)</span></nav><Link className={`button button-primary ${styles.addButton}`} href="/admin/podcast/new" aria-label="Add Podcast"><Plus size={15} />Add Podcast</Link></div>{episodes.length ? <div className={styles.grid}>{episodes.map((episode) => <article className={styles.card} key={episode.slug}><Link className={styles.imageWrap} href={`/admin/podcast/${episode.slug}`}><div className={styles.imagePlaceholder}><Headphones size={24} /></div><span className={`${styles.status} ${episode.status === "published" ? styles.statusPublished : styles.statusDraft}`}>{episode.status === "published" ? "Published" : "Draft"}</span></Link><div className={styles.body}><p className={styles.category}>Podcast</p><h2 className={styles.title}>{episode.title}</h2><div className={styles.meta}><span><CalendarDays size={12} />{episode.publishedAt}</span>{episode.duration ? <span><Clock3 size={12} />{episode.duration}</span> : null}</div></div><div className={styles.actions}><Link className={styles.action} href={`/admin/podcast/${episode.slug}`}>Edit</Link><Link className={styles.action} href={`/podcast/${episode.slug}`} target="_blank" aria-label={`Preview ${episode.title}`} title="Preview"><Eye size={15} /></Link><MediaMoreActions kind="podcast" slug={episode.slug} title={episode.title} status={episode.status} /></div></article>)}</div> : <div className={styles.empty}>No podcast episodes yet. Add your first episode to begin.</div>}</section>;
}
