import type { Book } from "./types";

export const books: Book[] = [
  {
    slug: "from-perfection-to-corruption",
    title: "From Perfection to Corruption",
    subtitle: "",
    author: "",
    publisher: "Spirit & Life",
    description: "",
    length: "",
    expectedPublication: "",
    category: "",
    status: "Coming Soon",
    tableOfContents: [],
  },
  {
    slug: "thy-word-is-truth",
    title: "Thy Word Is Truth",
    subtitle: "",
    author: "",
    publisher: "Spirit & Life",
    description: "",
    length: "",
    expectedPublication: "",
    category: "",
    status: "Coming Soon",
    tableOfContents: [],
  },
  {
    slug: "the-legal-protocols-of-god",
    title: "The Legal Protocols of God",
    subtitle: "",
    author: "",
    publisher: "Spirit & Life",
    description: "",
    length: "",
    expectedPublication: "",
    category: "",
    status: "Coming Soon",
    tableOfContents: [],
  },
  {
    slug: "when-man-acts-like-god",
    title: "When Man Acts Like God",
    subtitle: "",
    author: "",
    publisher: "Spirit & Life",
    description: "",
    length: "",
    expectedPublication: "",
    category: "",
    status: "Coming Soon",
    tableOfContents: [],
  },
];
