import "server-only";

import crypto from "node:crypto";
import { sql } from "@vercel/postgres";

export type DraftContentType = "reflection" | "journal" | "book";
export type ArticleDraftContentType = "article";
export type DraftStatus = "draft" | "published";

export type PublishedSnapshot = { title: string; slug: string; introduction: string | null; body: Record<string, unknown>; category: string | null; tags: string[]; image_reference: string | null; topics?: string[]; series?: string | null };
export type ContentDraft = { id: string; content_type: DraftContentType; title: string; slug: string; status: DraftStatus; introduction: string | null; body: Record<string, unknown>; category: string | null; tags: string[]; image_reference: string | null; created_at: string; updated_at: string; published_at: string | null; author_id: string | null; published_snapshot: PublishedSnapshot | null; has_unpublished_changes: boolean };
export type ArticleDraft = Omit<ContentDraft, "content_type"> & { content_type: ArticleDraftContentType; topics: string[]; series: string | null };
export type DraftInput = { contentType: DraftContentType; title: string; slug: string; introduction?: string; body?: Record<string, unknown>; category?: string; tags?: string[]; imageReference?: string; authorId?: string };
export type ArticleDraftInput = DraftInput & { contentType: ArticleDraftContentType; topics?: string[]; series?: string | null };
let schemaPromise: Promise<void> | null = null;
function nowIso() { return new Date().toISOString(); }
export function normalizeDraftSlug(value: string) { return value.trim().toLowerCase().normalize("NFKD").replace(/[\u0300-\u036f]/g, "").replace(/[^a-z0-9]+/g, "-").replace(/^-+|-+$/g, "").slice(0, 120).replace(/-+$/g, ""); }
export function isValidDraftSlug(value: string) { return /^[a-z0-9]+(?:-[a-z0-9]+)*$/.test(value) && value.length <= 120; }
async function ensureSchema() {
  if (!schemaPromise) schemaPromise = (async () => {
    await sql`CREATE TABLE IF NOT EXISTS content_drafts (id text PRIMARY KEY, content_type text NOT NULL CHECK (content_type IN ('reflection', 'journal', 'book', 'article')), title text NOT NULL, slug text NOT NULL, status text NOT NULL DEFAULT 'draft' CHECK (status IN ('draft', 'published')), introduction text, body jsonb NOT NULL DEFAULT '{}'::jsonb, category text, tags jsonb NOT NULL DEFAULT '[]'::jsonb, image_reference text, created_at timestamptz NOT NULL DEFAULT now(), updated_at timestamptz NOT NULL DEFAULT now(), published_at timestamptz, author_id text, published_snapshot jsonb, has_unpublished_changes boolean NOT NULL DEFAULT false, topics jsonb NOT NULL DEFAULT '[]'::jsonb, series text)`;
    await sql`ALTER TABLE content_drafts ADD COLUMN IF NOT EXISTS published_snapshot jsonb`;
    await sql`ALTER TABLE content_drafts ADD COLUMN IF NOT EXISTS has_unpublished_changes boolean NOT NULL DEFAULT false`;
    await sql`ALTER TABLE content_drafts ADD COLUMN IF NOT EXISTS topics jsonb NOT NULL DEFAULT '[]'::jsonb`;
    await sql`ALTER TABLE content_drafts ADD COLUMN IF NOT EXISTS series text`;
    await sql`DO $$ BEGIN ALTER TABLE content_drafts DROP CONSTRAINT IF EXISTS content_drafts_content_type_check; ALTER TABLE content_drafts ADD CONSTRAINT content_drafts_content_type_check CHECK (content_type IN ('reflection', 'journal', 'book', 'article')); EXCEPTION WHEN duplicate_object THEN NULL; END $$`;
    await sql`CREATE TABLE IF NOT EXISTS content_deletions (content_type text NOT NULL CHECK (content_type IN ('reflection', 'journal', 'book', 'article')), slug text NOT NULL, deleted_at timestamptz NOT NULL DEFAULT now(), PRIMARY KEY (content_type, slug))`;
    await sql`CREATE INDEX IF NOT EXISTS content_drafts_content_type_idx ON content_drafts (content_type)`;
    await sql`CREATE INDEX IF NOT EXISTS content_drafts_status_idx ON content_drafts (status)`;
    await sql`CREATE INDEX IF NOT EXISTS content_drafts_updated_at_idx ON content_drafts (updated_at DESC)`;
  })();
  await schemaPromise;
}
export async function listDrafts() { await ensureSchema(); const result = await sql<ContentDraft>`SELECT * FROM content_drafts WHERE status = 'draft' ORDER BY updated_at DESC`; return result.rows; }
export async function listAllDrafts(contentType?: DraftContentType) { await ensureSchema(); const result = contentType ? await sql<ContentDraft>`SELECT * FROM content_drafts WHERE content_type = ${contentType} ORDER BY updated_at DESC` : await sql<ContentDraft>`SELECT * FROM content_drafts ORDER BY updated_at DESC`; return result.rows; }
export async function listDeletedContentSlugs(contentType: DraftContentType) { await ensureSchema(); const result = await sql<{ slug: string }>`SELECT slug FROM content_deletions WHERE content_type = ${contentType}`; return new Set(result.rows.map((row) => row.slug)); }
export async function isContentDeleted(contentType: DraftContentType, slug: string) { await ensureSchema(); const result = await sql<{ slug: string }>`SELECT slug FROM content_deletions WHERE content_type = ${contentType} AND slug = ${normalizeDraftSlug(slug)} LIMIT 1`; return Boolean(result.rows[0]); }
export async function deleteContent(contentType: DraftContentType, slug: string) { await ensureSchema(); const normalizedSlug = normalizeDraftSlug(slug); await sql`DELETE FROM content_drafts WHERE content_type = ${contentType} AND (slug = ${normalizedSlug} OR published_snapshot->>'slug' = ${normalizedSlug})`; await sql`INSERT INTO content_deletions (content_type, slug, deleted_at) VALUES (${contentType}, ${normalizedSlug}, ${nowIso()}) ON CONFLICT (content_type, slug) DO UPDATE SET deleted_at = EXCLUDED.deleted_at`; }
function resolvePublishedContent(draft: ContentDraft): ContentDraft { if (!draft.published_snapshot) return draft; const snapshot = draft.published_snapshot; return { ...draft, title: snapshot.title, slug: snapshot.slug, introduction: snapshot.introduction, body: snapshot.body, category: snapshot.category, tags: snapshot.tags, image_reference: snapshot.image_reference }; }
export async function getDraft(id: string) { await ensureSchema(); const result = await sql<ContentDraft>`SELECT * FROM content_drafts WHERE id = ${id} LIMIT 1`; return result.rows[0] ?? null; }
export async function getDraftByTypeAndSlug(contentType: DraftContentType, slug: string) { await ensureSchema(); const normalizedSlug = normalizeDraftSlug(slug); const result = await sql<ContentDraft>`SELECT * FROM content_drafts WHERE content_type = ${contentType} AND slug = ${normalizedSlug} LIMIT 1`; return result.rows[0] ?? null; }
async function getAvailableDraftSlug(contentType: DraftContentType, requestedSlug: string) { const base = normalizeDraftSlug(requestedSlug) || "untitled"; if (!(await getDraftByTypeAndSlug(contentType, base))) return base; for (let suffix = 2; suffix <= 999; suffix += 1) { const suffixText = `-${suffix}`; const candidate = `${base.slice(0, Math.max(1, 120 - suffixText.length))}${suffixText}`; if (!(await getDraftByTypeAndSlug(contentType, candidate))) return candidate; } return `${base.slice(0, 114)}-${crypto.randomInt(100000, 999999)}`; }
export async function listPublishedDrafts(contentType?: DraftContentType) { await ensureSchema(); const result = contentType ? await sql<ContentDraft>`SELECT * FROM content_drafts WHERE status = 'published' AND content_type = ${contentType} ORDER BY published_at DESC NULLS LAST, updated_at DESC` : await sql<ContentDraft>`SELECT * FROM content_drafts WHERE status = 'published' ORDER BY published_at DESC NULLS LAST, updated_at DESC`; return result.rows.map(resolvePublishedContent); }
export async function getPublishedDraft(contentType: DraftContentType, slug: string) { await ensureSchema(); const normalizedSlug = normalizeDraftSlug(slug); const result = await sql<ContentDraft>`SELECT * FROM content_drafts WHERE status = 'published' AND content_type = ${contentType} AND COALESCE(published_snapshot->>'slug', slug) = ${normalizedSlug} LIMIT 1`; const row = result.rows[0]; return row ? resolvePublishedContent(row) : null; }

async function getAvailableArticleSlug(requestedSlug: string) { const base = normalizeDraftSlug(requestedSlug) || "untitled"; const exists = async (slug: string) => { const result = await sql<{ id: string }>`SELECT id FROM content_drafts WHERE content_type = 'article' AND slug = ${slug} LIMIT 1`; return Boolean(result.rows[0]); }; if (!(await exists(base))) return base; for (let suffix = 2; suffix <= 999; suffix += 1) { const suffixText = `-${suffix}`; const candidate = `${base.slice(0, Math.max(1, 120 - suffixText.length))}${suffixText}`; if (!(await exists(candidate))) return candidate; } return `${base.slice(0, 114)}-${crypto.randomInt(100000, 999999)}`; }
function resolvePublishedArticle(draft: ArticleDraft): ArticleDraft { if (!draft.published_snapshot) return draft; const snapshot = draft.published_snapshot; const body = snapshot.image_reference ? { ...snapshot.body, image: snapshot.image_reference } : snapshot.body; return { ...draft, title: snapshot.title, slug: snapshot.slug, introduction: snapshot.introduction, body, category: snapshot.category, tags: snapshot.tags, image_reference: snapshot.image_reference, topics: snapshot.topics ?? [], series: snapshot.series ?? null }; }
export async function getArticleDraft(id: string) { await ensureSchema(); const result = await sql<ArticleDraft>`SELECT * FROM content_drafts WHERE id = ${id} AND content_type = 'article' LIMIT 1`; return result.rows[0] ?? null; }
export async function getArticleDraftBySlug(slug: string) { await ensureSchema(); const normalizedSlug = normalizeDraftSlug(slug); const result = await sql<ArticleDraft>`SELECT * FROM content_drafts WHERE content_type = 'article' AND slug = ${normalizedSlug} LIMIT 1`; return result.rows[0] ?? null; }
export async function listArticleDrafts() { await ensureSchema(); const result = await sql<ArticleDraft>`SELECT * FROM content_drafts WHERE content_type = 'article' ORDER BY updated_at DESC`; return result.rows; }
export async function listPublishedArticles() { await ensureSchema(); const result = await sql<ArticleDraft>`SELECT * FROM content_drafts WHERE content_type = 'article' AND status = 'published' ORDER BY published_at DESC NULLS LAST, updated_at DESC`; return result.rows.map(resolvePublishedArticle); }
export async function getPublishedArticle(slug: string) { await ensureSchema(); const normalizedSlug = normalizeDraftSlug(slug); const result = await sql<ArticleDraft>`SELECT * FROM content_drafts WHERE content_type = 'article' AND status = 'published' AND COALESCE(published_snapshot->>'slug', slug) = ${normalizedSlug} LIMIT 1`; const row = result.rows[0]; return row ? resolvePublishedArticle(row) : null; }
export async function createArticleDraft(input: ArticleDraftInput) { await ensureSchema(); const id = crypto.randomUUID(); const timestamp = nowIso(); const slug = await getAvailableArticleSlug(input.slug); await sql`INSERT INTO content_drafts (id, content_type, title, slug, status, introduction, body, category, tags, image_reference, created_at, updated_at, published_at, author_id, topics, series) VALUES (${id}, 'article', ${input.title}, ${slug}, 'draft', ${input.introduction ?? null}, ${JSON.stringify(input.body ?? {})}::jsonb, ${input.category ?? null}, ${JSON.stringify(input.tags ?? [])}::jsonb, ${input.imageReference ?? null}, ${timestamp}, ${timestamp}, NULL, ${input.authorId ?? null}, ${JSON.stringify(input.topics ?? [])}::jsonb, ${input.series ?? null})`; return getArticleDraft(id); }
export async function updateArticleDraft(id: string, input: ArticleDraftInput) { await ensureSchema(); const slug = normalizeDraftSlug(input.slug); await sql`UPDATE content_drafts SET title = ${input.title}, slug = ${slug}, introduction = ${input.introduction ?? null}, body = ${JSON.stringify(input.body ?? {})}::jsonb, category = ${input.category ?? null}, tags = ${JSON.stringify(input.tags ?? [])}::jsonb, image_reference = ${input.imageReference ?? null}, topics = ${JSON.stringify(input.topics ?? [])}::jsonb, series = ${input.series ?? null}, has_unpublished_changes = (status = 'published'), updated_at = ${nowIso()} WHERE id = ${id} AND content_type = 'article'`; return getArticleDraft(id); }
export async function updateArticleDraftImage(id: string, imageReference: string) { await ensureSchema(); await sql`UPDATE content_drafts SET image_reference = ${imageReference}, has_unpublished_changes = (status = 'published'), updated_at = ${nowIso()} WHERE id = ${id} AND content_type = 'article'`; return getArticleDraft(id); }
export async function publishArticleDraft(id: string) { await ensureSchema(); const timestamp = nowIso(); const existing = await getArticleDraft(id); if (!existing) return null; await sql`UPDATE content_drafts SET status = 'published', published_snapshot = jsonb_build_object('title', title, 'slug', slug, 'introduction', introduction, 'body', body, 'category', category, 'tags', tags, 'image_reference', image_reference, 'topics', topics, 'series', series), has_unpublished_changes = false, published_at = COALESCE(published_at, ${timestamp}), updated_at = ${timestamp} WHERE id = ${id} AND content_type = 'article'`; await sql`DELETE FROM content_deletions WHERE content_type = 'article' AND slug IN (${existing.slug}, ${existing.published_snapshot?.slug ?? ""})`; return getArticleDraft(id); }
export async function unpublishArticleDraft(id: string) { await ensureSchema(); const existing = await getArticleDraft(id); if (!existing) return null; await sql`UPDATE content_drafts SET status = 'draft', has_unpublished_changes = false, updated_at = ${nowIso()} WHERE id = ${id} AND content_type = 'article'`; await sql`INSERT INTO content_deletions (content_type, slug, deleted_at) VALUES ('article', ${existing.slug}, ${nowIso()}) ON CONFLICT (content_type, slug) DO UPDATE SET deleted_at = EXCLUDED.deleted_at`; return getArticleDraft(id); }
