import "server-only";
import crypto from "node:crypto";
import { sql } from "@vercel/postgres";

export type PodcastEpisode = { id:string; slug:string; title:string; description:string; publishedAt:string; duration:string|null; coverImage:string|null; audioUrl:string|null; transcript:string|null; youtubeUrl:string|null; topicSlugs:string[]; seriesSlug:string|null; questionSlugs:string[]; articleSlugs:string[]; resourceSlugs:string[]; status:"draft"|"published" };
let schemaPromise: Promise<void>|null=null;
async function ensureSchema(){ if(!schemaPromise) schemaPromise=(async()=>{ await sql`CREATE TABLE IF NOT EXISTS podcast_episodes (id text PRIMARY KEY, slug text UNIQUE NOT NULL, title text NOT NULL, description text NOT NULL DEFAULT '', published_at timestamptz NOT NULL, duration text, cover_image text, audio_url text, transcript text, youtube_url text, topic_slugs jsonb NOT NULL DEFAULT '[]'::jsonb, series_slug text, question_slugs jsonb NOT NULL DEFAULT '[]'::jsonb, article_slugs jsonb NOT NULL DEFAULT '[]'::jsonb, resource_slugs jsonb NOT NULL DEFAULT '[]'::jsonb, status text NOT NULL DEFAULT 'draft' CHECK (status IN ('draft','published')), created_at timestamptz NOT NULL DEFAULT now(), updated_at timestamptz NOT NULL DEFAULT now())`; await sql`ALTER TABLE podcast_episodes ADD COLUMN IF NOT EXISTS youtube_url text`; await sql`ALTER TABLE podcast_episodes ADD COLUMN IF NOT EXISTS article_slugs jsonb NOT NULL DEFAULT '[]'::jsonb`; await sql`ALTER TABLE podcast_episodes ADD COLUMN IF NOT EXISTS resource_slugs jsonb NOT NULL DEFAULT '[]'::jsonb`; await sql`ALTER TABLE podcast_episodes ADD COLUMN IF NOT EXISTS cover_image text`; await sql`CREATE INDEX IF NOT EXISTS podcast_episodes_status_idx ON podcast_episodes(status)`; await sql`CREATE INDEX IF NOT EXISTS podcast_episodes_published_at_idx ON podcast_episodes(published_at DESC)`;})(); await schemaPromise; }
function jsonStrings(v:unknown){return Array.isArray(v)?v.map(String):[]}
function rowToEpisode(r:Record<string,unknown>):PodcastEpisode{return{id:String(r.id),slug:String(r.slug),title:String(r.title),description:String(r.description??""),publishedAt:new Date(String(r.published_at)).toISOString().slice(0,10),duration:r.duration?String(r.duration):null,coverImage:r.cover_image?String(r.cover_image):null,audioUrl:r.audio_url?String(r.audio_url):null,transcript:r.transcript?String(r.transcript):null,youtubeUrl:r.youtube_url?String(r.youtube_url):null,topicSlugs:jsonStrings(r.topic_slugs),seriesSlug:r.series_slug?String(r.series_slug):null,questionSlugs:jsonStrings(r.question_slugs),articleSlugs:jsonStrings(r.article_slugs),resourceSlugs:jsonStrings(r.resource_slugs),status:r.status==="published"?"published":"draft"}}
export async function listPodcastEpisodes(publishedOnly=true){await ensureSchema();const r=publishedOnly?await sql`SELECT * FROM podcast_episodes WHERE status='published' ORDER BY published_at DESC`:await sql`SELECT * FROM podcast_episodes ORDER BY updated_at DESC`;return r.rows.map(rowToEpisode)}
export async function getPodcastEpisodeBySlug(slug:string){await ensureSchema();const r=await sql`SELECT * FROM podcast_episodes WHERE slug=${slug} LIMIT 1`;return r.rows[0]?rowToEpisode(r.rows[0]):null}
export async function createPodcastEpisode(i:Omit<PodcastEpisode,"id"|"status">){await ensureSchema();const id=crypto.randomUUID();await sql`INSERT INTO podcast_episodes (id,slug,title,description,published_at,duration,cover_image,audio_url,transcript,youtube_url,topic_slugs,series_slug,question_slugs,article_slugs,resource_slugs) VALUES (${id},${i.slug},${i.title},${i.description},${i.publishedAt},${i.duration},${i.coverImage},${i.audioUrl},${i.transcript},${i.youtubeUrl},${JSON.stringify(i.topicSlugs)}::jsonb,${i.seriesSlug},${JSON.stringify(i.questionSlugs)}::jsonb,${JSON.stringify(i.articleSlugs)}::jsonb,${JSON.stringify(i.resourceSlugs)}::jsonb)`;return getPodcastEpisodeBySlug(i.slug)}
export async function updatePodcastEpisode(slug:string,i:Partial<Pick<PodcastEpisode,"title"|"description"|"publishedAt"|"duration"|"coverImage"|"audioUrl"|"transcript"|"youtubeUrl"|"topicSlugs"|"seriesSlug"|"questionSlugs"|"articleSlugs"|"resourceSlugs">>){await ensureSchema();await sql`UPDATE podcast_episodes SET title=COALESCE(${i.title??null},title),description=COALESCE(${i.description??null},description),published_at=COALESCE(${i.publishedAt??null},published_at),duration=${i.duration??null},cover_image=${i.coverImage??null},audio_url=COALESCE(${i.audioUrl??null},audio_url),transcript=${i.transcript??null},youtube_url=${i.youtubeUrl??null},topic_slugs=COALESCE(${i.topicSlugs?JSON.stringify(i.topicSlugs):null}::jsonb,topic_slugs),series_slug=${i.seriesSlug??null},question_slugs=COALESCE(${i.questionSlugs?JSON.stringify(i.questionSlugs):null}::jsonb,question_slugs),article_slugs=COALESCE(${i.articleSlugs?JSON.stringify(i.articleSlugs):null}::jsonb,article_slugs),resource_slugs=COALESCE(${i.resourceSlugs?JSON.stringify(i.resourceSlugs):null}::jsonb,resource_slugs),updated_at=now() WHERE slug=${slug}`;return getPodcastEpisodeBySlug(slug)}
export async function updatePodcastEpisodeStatus(slug:string,status:"draft"|"published"){await ensureSchema();await sql`UPDATE podcast_episodes SET status=${status},updated_at=now() WHERE slug=${slug}`;return getPodcastEpisodeBySlug(slug)}
export async function deletePodcastEpisode(slug:string){await ensureSchema();await sql`DELETE FROM podcast_episodes WHERE slug=${slug}`}
