import Link from "next/link";
import { CalendarDays, Eye, FileText, Plus } from "lucide-react";
import { listDownloadableResources } from "@/app/lib/resource-repository";
import { MediaMoreActions } from "@/app/admin/(protected)/content/media-more-actions";
import styles from "../content/admin-library-reference.module.css";

export default async function AdminResourcesPage() {
  const resources = await listDownloadableResources(false);
  const published = resources.filter((resource) => resource.status === "published").length;
  const drafts = resources.length - published;
  return <section className={styles.library}><div className={styles.heading}><div><h1>Downloads</h1><p>Write and manage PDFs and other downloadable resources for readers.</p></div></div><div className={styles.toolbar}><nav className={styles.tabs}><span className={`${styles.tab} ${styles.tabActive}`}>All ({resources.length})</span><span className={styles.tab}>Published ({published})</span><span className={styles.tab}>Drafts ({drafts})</span><span className={styles.tab}>Archived (0)</span></nav><Link className={`button button-primary ${styles.addButton}`} href="/admin/resources/new" aria-label="Add Download"><Plus size={15} />Add Download</Link></div>{resources.length ? <div className={styles.grid}>{resources.map((resource) => { const adminResourceUrl = `/admin/resources/${encodeURIComponent(resource.slug)}`; return <article className={styles.card} key={resource.slug}><Link className={styles.imageWrap} href={adminResourceUrl}><div className={styles.imagePlaceholder}><FileText size={24} /></div><span className={`${styles.status} ${resource.status === "published" ? styles.statusPublished : styles.statusDraft}`}>{resource.status === "published" ? "Published" : "Draft"}</span></Link><div className={styles.body}><p className={styles.category}>{resource.kind}</p><h2 className={styles.title}>{resource.title}</h2><div className={styles.meta}><span><CalendarDays size={12} />{resource.publishedAt}</span></div></div><div className={styles.actions}><Link className={styles.action} href={adminResourceUrl}>Edit</Link><Link className={styles.action} href={`/resources/${encodeURIComponent(resource.slug)}`} target="_blank" aria-label={`Preview ${resource.title}`} title="Preview"><Eye size={15} /></Link><MediaMoreActions kind="download" slug={resource.slug} title={resource.title} status={resource.status} /></div></article>; })}</div> : <div className={styles.empty}>No downloads yet. Add your first resource to begin.</div>}</section>;
}
