import Image from "next/image";
import Link from "next/link";
import { RelatedContent } from "@/app/components/related-content";
import { ReadingNavigation } from "@/app/components/reading-navigation";
import { ReadingProgress } from "@/app/components/reading-progress";
import { ArticleRichTextRenderer } from "@/app/components/article-rich-text-renderer";
import { listPublishedArticles } from "@/app/content/repository";
import type { Article } from "@/app/data/articles";
export async function ArticlePage({ article, showBackLink = true }: { article: Article; showBackLink?: boolean }) { const articles = await listPublishedArticles(); const index = articles.findIndex((item) => item.contentSlug === article.contentSlug); const previous = index > 0 ? articles[index - 1] : undefined; const next = index >= 0 && index < articles.length - 1 ? articles[index + 1] : undefined; return <main className="reflection-detail-page article-detail-page"><ReadingProgress /><article className="reflection-detail"><header className="reflection-detail-header page-container detail-header"><p className="eyebrow">Article</p><h1>{article.title}</h1><div className="reflection-meta"><span>{article.date}</span><span>{article.readingTime}</span><span>{article.category}</span></div></header><div className="reflection-feature-image page-container"><Image src={article.image} alt={article.title} width={1280} height={853} priority sizes="(max-width: 1220px) 100vw, 76rem" /></div><div className="reflection-reading-column"><p className="reflection-introduction">{article.introduction}</p>{article.richText ? <ArticleRichTextRenderer document={article.richText} /> : article.sections.map((section) => <section className="reading-section" key={section.heading}><h2>{section.heading}</h2>{section.paragraphs.map((paragraph) => <p key={paragraph}>{paragraph}</p>)}</section>)}<ReadingNavigation previous={previous ? { href: `/articles/${previous.contentSlug}`, title: previous.title } : undefined} next={next ? { href: `/articles/${next.contentSlug}`, title: next.title } : undefined} />{showBackLink ? <Link className="button button-text" href="/articles">Back to Articles</Link> : null}<RelatedContent relations={article} /></div></article></main>; }
