import type { Metadata } from "next";
import { pageMetadata } from "@/app/content/seo";

export const metadata: Metadata = pageMetadata("Privacy Policy", "The Spirit & Life privacy policy and future data practices.", "/privacy-policy");

export default function PrivacyPolicyPage() {
  return (
    <main className="page-container placeholder-page">
      <p className="eyebrow">Site Information</p>
      <h1>Privacy Policy</h1>
      <p>Spirit &amp; Life is a reading and study platform that values clarity, respect, and careful stewardship of any information you share.</p>
      <p>If you subscribe to the newsletter, your email address is stored so Spirit &amp; Life can send the updates you requested. You can unsubscribe from newsletter emails at any time.</p>
      <p>If you use the contact form, your name, email address, and message are stored so a reply can be prepared. This information is not shared with third parties.</p>
      <p>The site does not use personal information for advertising or third-party marketing. Standard server logs may be generated by the hosting environment.</p>
      <p>As the site develops, any future data practices will be described here before they are introduced.</p>
    </main>
  );
}
