import type { Metadata } from "next";
import { pageMetadata } from "@/app/content/seo";

export const metadata: Metadata = pageMetadata("Privacy Policy", "The Spirit & Life privacy policy and future data practices.", "/privacy-policy");

export default function PrivacyPolicyPage() {
  return (
    <main className="page-container placeholder-page">
      <p className="eyebrow">Site Information</p>
      <h1>Privacy Policy</h1>
      <p>Spirit &amp; Life is a reading and study platform that values clarity, respect, and careful stewardship of any information you share.</p>
      <p>At present, the site does not collect personal data for marketing or analytics beyond the standard server logs that may be generated by the hosting environment.</p>
      <p>If you use the contact form, the information you provide is used only to prepare a reply and is not shared with third parties.</p>
      <p>As the site develops, any future data practices will be described here before they are introduced.</p>
    </main>
  );
}
