import Link from "next/link";
import Image from "next/image";
import { ArrowRight, BookOpen, FilePenLine, FileText } from "lucide-react";
import { listAdminContentItems, type AdminContentItem } from "@/app/admin/(protected)/content/admin-content";
import type { DraftContentType } from "@/app/lib/content-drafts";
const sections: Array<{ contentType: DraftContentType; label: string }> = [{ contentType: "article", label: "Articles" }, { contentType: "reflection", label: "Reflections" }, { contentType: "journal", label: "Journals" }, { contentType: "book", label: "Books" }];
function statusLabel(item: AdminContentItem) { if (item.status === "published") return item.isStaticSource && !item.hasDraft ? "Published (static)" : item.hasUnpublishedChanges ? "Published (unpublished changes)" : "Published"; if (item.status === "draft") return item.isStaticSource ? "Draft (unpublished changes)" : "Draft"; return "Published (static)"; }
function sortRecentItems(items: AdminContentItem[]) { return [...items].sort((a, b) => (Date.parse(b.updatedAt ?? b.date ?? "") || 0) - (Date.parse(a.updatedAt ?? a.date ?? "") || 0)); }
export default async function AdminContentPage() { const itemsByType = Object.fromEntries(await Promise.all(sections.map(async (section) => [section.contentType, await listAdminContentItems(section.contentType)]))) as Record<DraftContentType, AdminContentItem[]>; const overview = sections.map((section) => ({ ...section, title: section.label, description: `Manage ${section.label.toLowerCase()}`, icon: section.contentType === "book" ? BookOpen : section.contentType === "article" ? FileText : section.contentType === "reflection" ? FilePenLine : FileText, count: itemsByType[section.contentType].filter((item) => item.status !== "draft").length, href: `/admin/content/${section.contentType}` })); const draftCount = Object.values(itemsByType).flat().filter((item) => item.status === "draft").length; return <section className="admin-content-page"><article className="admin-card admin-page-intro-card"><h2>Content Management Overview</h2><p>Browse and manage all content across Spirit &amp; Life.</p><div className="admin-content-overview-grid">{overview.map((item) => { const Icon = item.icon; return <article className="admin-content-overview-card" key={item.title}><span className="admin-icon"><Icon size={19} /></span><h3>{item.title}</h3><p>{item.description}</p><strong>{item.count}</strong><small>Published</small><Link href={item.href}>View all <ArrowRight size={14} /></Link></article>; })}<article className="admin-content-overview-card"><span className="admin-icon"><FilePenLine size={19} /></span><h3>Drafts</h3><p>Continue editing drafts</p><strong>{draftCount}</strong><small>Drafts</small><Link href="/admin/content?type=draft">View all <ArrowRight size={14} /></Link></article></div></article><article className="admin-card admin-recent-content"><div className="admin-panel-heading"><h2>Recent Content</h2><Link className="admin-outline-link" href="/admin/content">View all content <ArrowRight size={14} /></Link></div><div className="admin-recent-columns">{sections.map((section) => <div key={section.contentType}><h3>Recent {section.label}</h3><ul className="admin-content-list">{sortRecentItems(itemsByType[section.contentType]).slice(0, 5).map((item) => <li key={`${item.contentType}-${item.slug}`}><Link href={`/admin/content/${item.contentType}/${item.slug}`}><strong>{item.title}</strong><small>{item.category ?? statusLabel(item)}{item.date ? ` · ${item.date}` : ""}</small></Link></li>)}</ul>{!itemsByType[section.contentType].length ? <p className="quiet-note">Nothing here yet.</p> : null}</div>)}</div></article></section>; }
