import Link from "next/link";
import { ArrowLeft, ExternalLink, ShoppingBag } from "lucide-react";
import { notFound } from "next/navigation";
import { getPublishedBook } from "@/app/content/repository";

function StoreMark({ store }: { store: string }) {
  const normalized = store.toLowerCase();
  if (normalized.includes("amazon")) return <span className="store-wordmark amazon-mark">amazon<span className="amazon-smile">⌣</span></span>;
  if (normalized.includes("selar")) return <span className="store-wordmark selar-mark">selar</span>;
  return <span className="store-initial">{store.trim().charAt(0).toUpperCase() || "S"}</span>;
}

export default async function GetBookPage({ params }: { params: Promise<{ slug: string }> }) {
  const { slug } = await params;
  const book = await getPublishedBook(slug);
  if (!book) notFound();
  const options = (book.purchaseOptions ?? []).filter((option) => option.enabled);
  const paperbackAvailable = book.paperbackStatus === "Available" && Boolean(book.paperbackUrl);
  return <main className="book-get-page"><section className="book-get-shell">
    <Link className="book-get-back" href={`/books/${book.contentSlug}`}><ArrowLeft size={15} /> Back to book</Link>
    <div className="book-get-header"><div className="book-get-icon"><ShoppingBag size={25} /></div><p className="eyebrow">Get the book</p><h1>Choose where to get your copy</h1><p>Purchase <strong>{book.title}</strong> from one of the available stores below. You will complete your purchase on the store's website.</p></div>
    <div className="book-store-grid">{options.length ? options.map((option) => <a className="book-store-card" key={option.id} href={option.url} target="_blank" rel="noopener noreferrer"><span className="book-store-brand"><StoreMark store={option.store} /></span><span className="book-store-copy"><strong>{option.store}</strong><small>Purchase this book</small></span><span className="book-store-arrow"><ExternalLink size={17} /></span></a>) : <div className="book-no-stores"><strong>Purchase links coming soon.</strong><span>This book is available, but store links have not been added yet.</span></div>}</div>
    <section className="paperback-card"><div><p className="eyebrow">Paperback edition</p><h2>{paperbackAvailable ? "Get the printed edition" : "Paperback coming soon"}</h2><p>{paperbackAvailable ? "The printed edition is available through the external store below." : "The paperback edition is being prepared and will be available soon."}</p></div>{paperbackAvailable ? <a className="button button-primary" href={book.paperbackUrl} target="_blank" rel="noopener noreferrer">Get paperback <ExternalLink size={15} /></a> : <span className="paperback-status">Available soon</span>}</section>
  </section><style>{`.book-get-page{min-height:100vh;background:var(--background);padding:clamp(2rem,5vw,5rem) 1rem}.book-get-shell{width:min(100%,62rem);margin:auto}.book-get-back{display:inline-flex;align-items:center;gap:.45rem;color:var(--muted);text-decoration:none;font-size:.9rem;margin-bottom:3rem}.book-get-back:hover{color:var(--foreground)}.book-get-header{max-width:44rem;margin-bottom:2.5rem}.book-get-icon{display:grid;place-items:center;width:3.1rem;height:3.1rem;border:1px solid color-mix(in srgb,var(--accent) 40%,var(--line));border-radius:50%;color:var(--accent);margin-bottom:1.3rem}.book-get-header h1{font-size:clamp(2.5rem,6vw,4.6rem);line-height:.95;letter-spacing:-.045em;margin:.4rem 0 1rem}.book-get-header>p:last-child{color:var(--muted);line-height:1.75;font-size:1.03rem}.book-store-grid{display:grid;gap:1rem}.book-store-card{display:grid;grid-template-columns:5rem 1fr auto;align-items:center;gap:1.2rem;padding:1.15rem 1.25rem;border:1px solid var(--line);background:var(--surface);color:var(--foreground);text-decoration:none;box-shadow:0 .7rem 2rem var(--shadow);transition:transform 180ms ease,border-color 180ms ease}.book-store-card:hover{transform:translateY(-2px);border-color:color-mix(in srgb,var(--accent) 55%,var(--line))}.book-store-brand{display:grid;place-items:center;min-height:3rem}.store-wordmark{font-weight:800;font-size:1.25rem;letter-spacing:-.04em}.amazon-mark{font-family:Arial,sans-serif}.amazon-smile{display:block;font-size:1.25rem;line-height:.25;margin-left:2rem}.selar-mark{font-weight:900}.store-initial{display:grid;place-items:center;width:2.8rem;height:2.8rem;border-radius:.7rem;background:var(--surface-muted);font-weight:800;color:var(--accent)}.book-store-copy{display:grid;gap:.2rem}.book-store-copy strong{font-size:1.05rem}.book-store-copy small{color:var(--muted)}.book-store-arrow{color:var(--accent)}.book-no-stores{display:grid;gap:.35rem;padding:1.5rem;border:1px dashed var(--line);background:var(--surface);color:var(--muted)}.book-no-stores strong{color:var(--foreground)}.paperback-card{display:flex;align-items:center;justify-content:space-between;gap:2rem;margin-top:3rem;padding:1.5rem;border:1px solid var(--line);background:var(--surface);box-shadow:0 .7rem 2rem var(--shadow)}.paperback-card h2{margin:.25rem 0 .45rem;font-size:1.4rem}.paperback-card p:not(.eyebrow){margin:0;color:var(--muted);line-height:1.6}.paperback-status{white-space:nowrap;padding:.55rem .8rem;border:1px solid var(--line);border-radius:999px;color:var(--muted);font-size:.8rem;font-weight:700}@media(max-width:650px){.book-store-card{grid-template-columns:3.5rem 1fr auto}.paperback-card{align-items:flex-start;flex-direction:column}.book-get-back{margin-bottom:2rem}}`}</style></main>;
}
