import { notFound, redirect } from "next/navigation";
import Link from "next/link";
import { getDraftByTypeAndSlug, isContentDeleted } from "@/app/lib/content-drafts";
import { draftToArticlePreview } from "@/app/content/published-draft-adapter";
import { articles } from "@/app/data/articles";
import { ArticlePage } from "@/app/components/article-page";
import { ArticlePublishForm } from "@/app/admin/(protected)/content/article-publish-form";
import { startEditingContentAction } from "@/app/admin/(protected)/actions/content";
export const dynamic = "force-dynamic";
export default async function AdminArticlePage({ params, searchParams }: { params: Promise<{ slug: string }>; searchParams: Promise<{ view?: string }> }) { const { slug } = await params; const { view } = await searchParams; const draft = await getDraftByTypeAndSlug("article", slug); if (!draft && await isContentDeleted("article", slug)) notFound(); if (view === "edit") redirect(`/admin/content/article/${slug}/edit`); const staticArticle = articles.find((item) => item.contentSlug === slug); const article = (draft ? draftToArticlePreview(draft) : null) ?? staticArticle; if (!article) notFound(); return <section className="admin-stack"><article className="admin-card"><div className="admin-header-row"><div><p className="eyebrow">Article</p><h2>{article.title}</h2></div><Link className="button button-secondary" href="/admin/content/article">Back to Articles</Link></div><nav className="admin-tab-row"><Link className="admin-tab is-active" href={`/admin/content/article/${slug}`}>Preview</Link>{draft ? <Link className="admin-tab" href={`/admin/content/article/${slug}/edit`}>Edit</Link> : <form action={startEditingContentAction}><input type="hidden" name="contentType" value="article" /><input type="hidden" name="slug" value={slug} /><button className="admin-tab" type="submit">Edit</button></form>}</nav>{draft ? <><p className="quiet-note">{draft.status === "published" ? draft.has_unpublished_changes ? "This article is live with unpublished changes saved." : "This article is published and live on the public site." : "This article is an unpublished draft."}</p><ArticlePublishForm draftId={draft.id} status={draft.status} hasUnpublishedChanges={draft.has_unpublished_changes} /></> : <p className="quiet-note">This is existing static article content.</p>}</article><article className="admin-card admin-preview"><ArticlePage article={article} showBackLink={false} /></article></section>; }
