import Link from "next/link";
import { notFound } from "next/navigation";
import { updatePodcastEpisodeAction } from "@/app/admin/(protected)/actions/podcast-manage";
import { getPodcastEpisodeBySlug } from "@/app/lib/podcast-repository";

export default async function AdminPodcastEpisodePage({ params }: { params: Promise<{ slug: string }> }) {
  const { slug } = await params;
  const episode = await getPodcastEpisodeBySlug(slug);
  if (!episode) notFound();
  return <section className="admin-editor-page"><div className="admin-editor-header"><div><Link className="admin-outline-link" href="/admin/podcast">← Back to Podcast</Link><p className="eyebrow">Edit</p><h1>{episode.title}</h1><p>Update the episode, show notes, audio details, or transcript.</p></div></div><article className="admin-editor-card"><form action={async (formData) => { await updatePodcastEpisodeAction(formData); }} className="space-y-5"><input type="hidden" name="slug" value={episode.slug} /><input name="title" required defaultValue={episode.title} className="w-full rounded-md border p-3" placeholder="Episode title" /><textarea name="description" className="min-h-32 w-full rounded-md border p-3" defaultValue={episode.description} placeholder="Description / show notes" /><div className="grid gap-4 sm:grid-cols-2"><input name="publishedAt" required type="date" defaultValue={episode.publishedAt} className="rounded-md border p-3" /><input name="duration" defaultValue={episode.duration ?? ""} className="rounded-md border p-3" placeholder="Duration" /></div><textarea name="transcript" className="min-h-40 w-full rounded-md border p-3" defaultValue={episode.transcript ?? ""} placeholder="Transcript" /><div className="rounded-xl border p-4"><p className="text-sm font-medium">Audio</p>{episode.audioUrl ? <audio className="mt-3 w-full" controls src={episode.audioUrl} /> : <p className="mt-2 text-sm text-muted-foreground">No audio file attached.</p>}<input type="hidden" name="audioUrl" value={episode.audioUrl ?? ""} /></div><div className="flex gap-3"><button type="submit" className="rounded-md border px-4 py-2">Save changes</button><Link href={`/podcast/${episode.slug}`} target="_blank" className="rounded-md border px-4 py-2">Preview</Link></div></form></article></section>;
}
